springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    path: /swagger-ui.html
    url: /openapi.yaml
    disable-swagger-default-url: true
    query-config-enabled: true
  show-actuator: true

app:
  command-context:
    #define the tabletop dimensions here
    table-top:
      width: 5
      height: 5

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG  # Logs detailed web request/response handling
    au.chipomho.robot: DEBUG        # Logs your specific business logic
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [traceId=%X{traceId} txId=%X{transactionId} spanId=%X{spanId}] %-5level %logger{36} - %msg%n"
